# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [10]:
%run initialise.py

Exception: File `'initialise.py'` not found.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [11]:
print(np.__version__) #__version__
print(np.__config__.show()) #__config__.show() 

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/faten/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/faten/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/faten/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/faten/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/faten/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/faten/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/faten/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/faten/anaconda3\\Library\\include']
None


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
zero_array=np.zeros(10,)
print(zero_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
print(zero_array.nbytes)
print(zero_array.size * zero_array.itemsize)
print(np.prod(zero_array.shape) * zero_array.itemsize) #bytes = size * itemize

80
80
80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [72]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

Exception: File `'`python.py'` not found.

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [23]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
n1 = np.arange(10,50)
print(n1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
n1[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [28]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [43]:
#방법1
#mat = np.array([1,2,0,0,4,0])
#np.where(mat != 0)

#방법2
np.nonzero([1,2,0,0,4,0]) #0이 아닌 vector의 위치

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [45]:
#방법1
#mat1 = np.identity(3)
#print(mat1)

#방법2
mat2 = np.eye(3) #np.eye() : identitiy matrix
print(mat2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
mat = np.random.random((3, 3, 3)) #random module, random function
print(mat)

[[[0.99854144 0.95847825 0.28700385]
  [0.40265156 0.28873695 0.74668252]
  [0.89646066 0.92679143 0.1952319 ]]

 [[0.93683767 0.29063109 0.70142271]
  [0.28470392 0.89947796 0.80095018]
  [0.30938805 0.72050444 0.91588547]]

 [[0.80325556 0.21100941 0.88069643]
  [0.91967399 0.54500845 0.95749778]
  [0.55518805 0.4855325  0.00247462]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
mat = np.random.random((10, 10))
print('minimum value: {}'.format(np.round(mat.min(), 4))) #.min()
print('maximum value: {}'.format(np.round(mat.max(), 4))) #.max()

minimum value: 0.0
maximum value: 0.9857


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [35]:
vec = np.random.random(30)
print(vec)
print(vec.mean()) #.mean()

[0.31545038 0.28710974 0.68783576 0.3634689  0.22113541 0.74897032
 0.52494585 0.38732877 0.00306882 0.87759945 0.75331866 0.86413108
 0.80532751 0.95319468 0.5081134  0.74514711 0.14549259 0.68242841
 0.77167719 0.10631042 0.78794461 0.41706212 0.17752894 0.21814486
 0.86047126 0.75883192 0.52703476 0.32463599 0.15666426 0.59380354]
0.5191392243166919


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
mat = np.ones((5, 5)) # 1로 구성된 10x10
mat[1:-1, 1:-1] = 0 # 가장 바깥쪽 행, 열을 제외하고 나머지 성분을 0으로
print(mat)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [48]:
mat = np.ones((3, 3)) # 1로 구성된 3x3
mat = np.pad(mat, pad_width=1, mode='constant', constant_values = 0) 
# .pad() : 행렬 채우기
# pad_width : 가장자리를 채울 열의 개수
# mode = 'constant' : 상수로 채운다, 그 값은 0 (constant_values)
print(mat) 

#방법2
# z = np.zeros((7,7))
# z[1:-1,1:-1] = 1 


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [52]:
print(0 * np.nan) # .nan : 정의할 수 없는 수
print(np.nan == np.nan) # 동등성이 정의되지 않음 -> false
print(np.inf > np.nan) # inf : 무한대
print(np.nan - np.nan) #nan 끼리의 계산은 nan
print(np.nan in set([np.nan])) #[np.nan] 집합에 np.nan 있음
print(0.3 == 3 * 0.1) # 부동소수점 때문에 false (3 * 0.1 = 0.30000000000000004)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [53]:
mat = np.diag([1, 2, 3, 4], k = -1) # k = -1 : (1,0)에서 대각으로 시작, k 제외 대각행렬 만듦
print(mat)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [54]:
mat = np.zeros((8, 8), dtype=int)
# mat[A::B] : A로 시작하는 index에서 B만큼의 step size로 slicing
mat[::2, 1::2] = 1 # 0행부터 2행씩 점프한 행 =1 and 1열부터 2열씩 점프한 열 =1
mat[1::2, ::2] = 1 # 1행부터 2행씩 점프한 행 =1 and 0열부터 2열씩 점프한 열 = 1
print(mat)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [59]:
z = np.unravel_index(100, (6,7,8))
# np.unrabel_index(indices, dims, order=‘C’) 
# C = 행 주요 /  F = 열 주요

# a = np.arange(12).reshape(3,4) 에서 index(1,2) = 6
# unravel_index 는 반대의 개념
 
print(z)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [19]:
z = np.tile(np.array([[0,1],[1,0]]), (4,4)) 
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [20]:
x = np.random.random((5,5))
normalize = (x - np.mean(x))/np.std(x)
print(normalize)

[[-1.10740881  0.73431537 -1.70949491 -0.18787852  0.54884396]
 [-0.51761458  0.56727439  1.45781753 -0.55005294  1.39343842]
 [ 0.81211175 -0.77832865  0.38154923  1.52873506  1.18486371]
 [-1.38703039  1.26000168 -0.41721616 -0.71043528 -1.62074607]
 [-0.93172206  0.42368807  0.68921809 -1.22436306  0.16043417]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [76]:
color = np.dtype([('r', np.ubyte),
                  ('g', np.ubyte),
                  ('b', np.ubyte),
                  ('a', np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [23]:
x = np.arange(15).reshape((5, 3))
y = np.arange(6).reshape((3, 2))
np.dot(x, y) # np.dot()

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [24]:
z = np.arange(11)
z[(z>3) & (z<8)] *= -1 
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [25]:
print(sum(range(5),-1))
from numpy import * # module 이름을 사용하지 않고 함수 가져오기
print(sum(range(5),-1)) # np.sum(range(5),-1)

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [64]:
Z = np.arange(3)
print(Z**Z)
print(2 << Z >> 2) # << : bit단위로 왼쪽으로 밀기 
print(Z <- Z)
print(1j*Z) # 1j : 복소수
print(Z/1/1)
print(Z<Z>Z) #print(Z<Z>Z) is illegal

[1 1 4]
[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
print(np.array(0) / np.array(0)) # array 나누기는 불가능
print(np.array(0) // np.array(0)) # 몫(정수 부분)만 취하는 것은 가능
print(np.array([np.nan]).astype(int).astype(float)) 

nan
0
[-2.14748365e+09]


<ipython-input-29-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-29-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [66]:
x = np.random.uniform(-10, +10, 10) # 균등분포 (low, high, size)
np.copysign(np.ceil(np.abs(x)), x) # .ceil() : 올림 copysign() : 해당 값을 기존 z의 부호대로 바꾼다

array([10.,  6., -4., -1.,  4., -6.,  9., -7., -5., -7.])

#### 30. How to find common values between two arrays? (★☆☆)

In [32]:
A = np.random.randint(0,10,10)
B = np.random.randint(0,10,10) # randint()
print(A,B)
print(np.intersect1d(A,B)) #intersect1d() : 공통된 인자 추출

[6 9 4 8 5 0 1 2 0 7] [4 9 0 7 5 9 9 8 2 3]
[0 2 4 5 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [67]:
# Suicide mode on
defaults = np.seterr(all="ignore") # 오류 무시
z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults) # **defaults : 원래대로 돌려놓음

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [35]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
# false
# np.sqrt(-1) = nan, np.emath.sqrt(-1) = 1j 

False


<ipython-input-35-c6ff0ad7fd7b>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [38]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D') #'D' : day 
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')

print(yesterday)
print(today)
print(tomorrow)

2021-09-12
2021-09-13
2021-09-14


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [4]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]') 
print(Z)
# 특정한 규칙에 따라 증가하는 수열
# dtype=‘datetime64[D]

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [8]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B, out=B) # add(A,B,out) : A와 B를 더하고 B에 그 값을 할당
np.divide(A,2,out=A) # divide(A,2,out) : A/2하고 A에 할당
np.negative(A,out=A) # negative(A,out) : A에 음수를 붙여 A에 할당
np.multiply(A,B,out=A) # multiply(A,B,out) : A,B를 곱한 것을 A에 할당

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [10]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1) 
print(np.floor(Z)) # floor() : 내림
print(np.ceil(Z)) # ceil() : 올림
print(Z.astype(int)) # astype() : 형 변환
print(np.trunc(Z)) #trunc(): 소숫자리를 자른 후의 value

[2. 2. 2. 9. 5. 7. 4. 2. 3. 5.]
[2. 2. 2. 9. 5. 7. 4. 2. 3. 5.]
[ 3.  3.  3. 10.  6.  8.  5.  3.  4.  6.]
[2 2 2 9 5 7 4 2 3 5]
[2. 2. 2. 9. 5. 7. 4. 2. 3. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [13]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)
# 0을 다 채워주고 숫자만큼 더해서 나타낸다

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [14]:
def generator(): # 대용량 자료 처리에 적합
    for i in range(10):
        yield i # yield : return과 비슷, generator 반환
Z = np.fromiter(generator(),dtype="float",count=-1) #numpy.fromiter(iterable, dtype, count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [20]:
Z = np.linspace(0,1,11,endpoint=False)[1:] 
#endpoint = False : 마지막을 지정 수가 아닌 수로 변환
#[1:] : 첫 번째 벡터를 없애서 10개 맞춘다
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [24]:
Z = np.random.random(10)
Z.sort() # sort() : 배열 정렬, 반환값은 None
print(Z)

[0.0325199  0.3017121  0.34182444 0.43013045 0.58395401 0.76405983
 0.86042712 0.86817275 0.93047594 0.95257207]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [25]:
Z = np.arange(10)
np.add.reduce(A) #배열의 차원을 축소시킨다

-4.5

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [28]:
A = np.random.randint(0,5,5)
B = np.random.randint(0,5,5)
#print(np.allclose(A,B)) : 허용 오차 가능
print(np.array_equal(A,B)) #array_equal() : 정확히 일치

False


#### 43. Make an array immutable (read-only) (★★☆)

In [29]:
z = np.zeros(10)
z.flags.writeable = False # flags.writeable = False : 쓰기 불가능 (read only)
z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [31]:
z = np.random.random((10,2))
x,y = z[:,0], z[:,1] 
r = np.sqrt(x**2+y**2) # cartesian coordinates
p = np.arctan2(y,x) #arctan2 : polar coordinates 
print(r)
print(p)

[1.06781999 1.15171949 1.00492676 0.97983104 0.86938843 0.86800092
 1.12406509 1.13288783 0.758938   0.62753385]
[0.70787852 0.64517149 0.41722678 0.25984674 0.76188984 0.10149345
 0.8854453  0.86854542 0.27301632 1.05741107]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
Z = np.random.random(10)
Z[Z.argmax()] = 0 # argmax() :최대값의 위치 인덱싱
print(Z)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [32]:
Z = np.zeros((5,5), dtype = [('x',float),('y',float)])
Z['x'],Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [33]:
x = np.arange(4)
y = x + 0.5
c = 1.0 / np.subtract.outer(x,y) #subtract.outer(xi,yj): 각 i,j에 대핟아흔 성분을 추출해서 뺀다
print(np.linalg.det(c)) #linalg : linear algebra, det : 행렬식

44.384169312169305


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [34]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min) ##iinfo() : int에 대한 정보
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min) #finfo() : float에 대한 정보 
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps) #eps : 표현 가능한 가장 작은 값

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [46]:
np.set_printoptions(threshold=float("inf"), precision=3) 
#threshold : 1개의 배열당 보여지는 요소의 총 개수 (요약하는 배열 요소의 총 수)
#precision : 출력 형태
Z = np.random.random(100)
print(Z)

[0.688 0.698 0.825 0.173 0.728 0.008 0.994 0.639 0.986 0.303 0.064 0.909
 0.474 0.011 0.365 0.178 0.254 0.484 0.53  0.514 0.12  0.418 0.165 0.47
 0.616 0.547 0.278 0.303 0.532 0.37  0.22  0.829 0.056 0.414 0.641 0.304
 0.023 0.717 0.54  0.377 0.06  0.982 0.969 0.268 0.984 0.49  0.223 0.17
 0.169 0.425 0.023 0.539 0.08  0.653 0.446 0.434 0.772 0.525 0.758 0.942
 0.111 0.19  0.234 0.73  0.234 0.484 0.082 0.039 0.578 0.828 0.696 0.325
 0.209 0.541 0.286 0.235 0.308 0.877 0.614 0.239 0.997 0.254 0.409 0.849
 0.239 0.754 0.733 0.788 0.209 0.612 0.078 0.87  0.004 0.472 0.476 0.132
 0.982 0.978 0.928 0.511]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [49]:
Z = np.arange(100)
a = np.random.uniform(0,100)
print(Z)
print(a)
print(Z[(np.abs(Z-a)).argmin()])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
48.65294978414369
49


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [4]:
import numpy as np
z = np.zeros(10, [('position', [('x', float,(1,)),
                               ('y', float,(1,))]),
                 ('color', [('r', float,(1,)),
                            ('g', float,(1,)),
                            ('b', float,(1,))])])
print(z)

[(([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [27]:
Z = np.random.random((10,2)) # .random() : 0부터 1사이의 수를 random으로 (10,2) 로 추출
X,Y = np.atleast_2d(Z[:,0], Z[:,1]) # np.atleast_2d() : 입력값을 2차원 이상 배열로
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2) # .T : transpose
print(D)

[[0.         0.38846237 0.92790512 0.81432697 0.35526406 0.25766485
  0.83531306 0.64576295 0.67122489 0.30554928]
 [0.38846237 0.         0.74208747 0.80783956 0.06262485 0.44705516
  0.7558521  0.26742132 0.73650302 0.14057295]
 [0.92790512 0.74208747 0.         0.39294039 0.80123265 0.73119011
  0.24037927 0.62110195 0.5197536  0.86770955]
 [0.81432697 0.80783956 0.39294039 0.         0.85028335 0.56211975
  0.15262377 0.81673878 0.17857268 0.89038366]
 [0.35526406 0.06262485 0.80123265 0.85028335 0.         0.45035982
  0.8058651  0.32152318 0.76870096 0.07933765]
 [0.25766485 0.44705516 0.73119011 0.56211975 0.45035982 0.
  0.60035066 0.63766425 0.41370341 0.44470196]
 [0.83531306 0.7558521  0.24037927 0.15262377 0.8058651  0.60035066
  0.         0.71907248 0.29455807 0.85719853]
 [0.64576295 0.26742132 0.62110195 0.81673878 0.32152318 0.63766425
  0.71907248 0.         0.80343342 0.39965965]
 [0.67122489 0.73650302 0.5197536  0.17857268 0.76870096 0.41370341
  0.29455807 0.80343

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [31]:
Z = np.arange(10, dtype=np.float32) # dtype() :데이터 타입 지정
print(Z) 
Z = Z.astype(np.int32, copy=False) # astype() : 데이터 타입 변경
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [34]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")

Z = np.genfromtxt(s,delimiter=",", dtype=np.int32) # genfromtxt : 텍스트 파일 읽기, delimiter : 구분문자 
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [41]:
Z = np.arange(9).reshape(3,3)
print(Z)
print('\n')

#1
for index, value in np.ndenumerate(Z): # np.ndenumerate(배열) : 다차원 index 반복, 배열 좌표와 값의 쌍
    print(index,value)
print('\n')

#2
for index in np.ndindex(Z.shape): # np.ndindex(모양) : 배열을 인덱싱하는 N차원 반복
    print(index,Z[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]]


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [49]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10)) 
D = np.sqrt(X*X+Y*Y) # X, Y 거리
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) ) # 정규분포 확률밀도함수
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [50]:
n = 10
p = 3
Z = np.zeros((n,n)) 
np.put(Z, np.random.choice(range(n*n), p, replace=False),1) 

print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [53]:
x = np.random.rand(5, 10) 
y = x - x.mean(axis=1, keepdims=True) 

print(y)

[[ 0.28218213 -0.3765382  -0.08327555 -0.04439765  0.15702631 -0.01496401
  -0.16015191 -0.16741811  0.1484109   0.2591261 ]
 [ 0.41159271  0.30081023  0.11487351  0.41811445 -0.33322994  0.30541966
  -0.35902509 -0.51971153  0.17552186 -0.51436588]
 [ 0.50384459  0.3436635  -0.3110878  -0.0610369  -0.39351078 -0.24654813
   0.30124646  0.07997658 -0.37609656  0.15954906]
 [-0.62173505  0.27771982  0.04851335  0.05317871  0.10587856  0.3333916
  -0.02903156 -0.15782154  0.29388888 -0.30398277]
 [-0.41341125 -0.42491603  0.08280012  0.13260719 -0.23697084  0.11890103
   0.13852101 -0.02093364  0.23330083  0.39010158]]


#### 59. How to sort an array by the nth column? (★★☆)

In [59]:
z = np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

# 열을 순서대로 정렬( 1,7,2 -> 1,2,7) - > 바뀐 인덱스에 따라 행 바꾸기

[[1 1 3]
 [4 7 2]
 [8 2 1]]
[[1 1 3]
 [8 2 1]
 [4 7 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [66]:
z= np.random.randint(0,3,(3,10))
print(z)
print((~z.any(axis=0)).any()) #any(): 하나라도 True 있으면 True 반환 cf) all() 

[[0 0 2 0 1 0 0 0 1 0]
 [2 0 2 1 0 0 0 2 1 2]
 [2 0 1 0 0 2 0 2 2 0]]
True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [77]:
z1 = np.random.uniform(0,1,10)
z2 = 0.5
m = z1.flat[np.abs(z1-z2).argmin()] 

print(m)

0.5024195128607142


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [107]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
iterator = np.nditer([A,B,None]) # nditer() : for문을 단순화해서 고차원 배열의 전체 항목 출력

for x,y,z in iterator:
    z = x + y
print(iterator.operands[2]) # operands[n] : n번째 피연산자 

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [2]:
# 이름 속성을 가진 배열 클래스 생성

# 클래스 변수 : 클래스 내부에 선언된 변수, 인스턴스 간에 서로 공유
# 인스턴스 변수 : self가 붙은 변수, 클래스의 인스턴스가 생성될 때 생성, 인스턴스 고유의 값(비밀)

import numpy as np 
class NamedArray(np.ndarray): 
    def __new__(cls, array, name="no name"): 
        obj = np.asarray(array).view(cls) 
        obj.name = name  
        return obj
    def __array_finalize__(self, obj): 
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")  
      
z = NamedArray(np.arange(10), "range_10")
print (z.name)


range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [116]:
z = np.ones(10)
print("원본 배열:", z)
a = np.random.randint(0,len(z),20)
np.add.at(z,a,1) # add.at (배열, 인덱스, 더할 배열) : z배열의 인덱스 위치에 1 더하기
print("더할 인덱스:" ,a)
print("완성된 배열:", z)

원본 배열: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
더할 인덱스: [9 1 3 0 9 1 0 9 8 8 3 0 8 7 1 9 3 6 2 6]
완성된 배열: [4. 4. 2. 4. 1. 1. 3. 2. 4. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [124]:
X = [1,2,3,4,5,6]
I = [3,4,5,6,7,8]
F = np.bincount(I,X) # bincount() : 0부터 가장 큰 값까지 각각의 발생 빈도수
print(F)

[0. 0. 0. 1. 2. 3. 4. 5. 6.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [147]:
w,h = 16, 16
img = np.random.randint(0,2,(w,h,3)).astype(np.ubyte) 
# astype() : 데이터 타입 변경, ubyte : unsigned char
# 3차원 : 16 = layer , 16 = row, 3 = col

F = img[...,0]*(256*256) + img[...,1]*256 + img[...,2] 
# ... : 차원이 너무 많을 때 쓴다 ex) x[1,2, ...] == x[1,2,:,:,:]
# pixel : 256 * 256
print(np.unique(F)) # unique(): 오름차순으로 고유값 반환 (중복 요소 제거시 사용)
print("고유 색상의 수:", len(np.unique(F))) 


[    0     1   256   257 65536 65537 65792 65793]
고유 색상의 수: 8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)